version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: tts_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "54322:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
